# Generated by Django 4.1.9 on 2023-05-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterfaceTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50, unique=True)),
                ('active', models.BooleanField()),
                ('title', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('title_visible', models.BooleanField()),
                ('logo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('logo_visible', models.BooleanField()),
                ('css_header_background_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('title_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_header_text_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_header_link_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_header_link_hover_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_module_background_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_module_text_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_module_link_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_module_link_hover_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_module_rounded_corners', models.BooleanField()),
                ('css_generic_link_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_generic_link_hover_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_save_button_background_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_save_button_background_hover_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_save_button_text_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_delete_button_background_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_delete_button_background_hover_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_delete_button_text_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('list_filter_dropdown', models.BooleanField()),
                ('related_modal_active', models.BooleanField()),
                ('related_modal_background_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('related_modal_rounded_corners', models.BooleanField()),
                ('logo_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('recent_actions_visible', models.BooleanField()),
                ('favicon', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('related_modal_background_opacity', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=5)),
                ('env_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('env_visible_in_header', models.BooleanField()),
                ('env_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('env_visible_in_favicon', models.BooleanField()),
                ('related_modal_close_button_visible', models.BooleanField()),
                ('language_chooser_active', models.BooleanField()),
                ('language_chooser_display', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('list_filter_sticky', models.BooleanField()),
                ('form_pagination_sticky', models.BooleanField()),
                ('form_submit_sticky', models.BooleanField()),
                ('css_module_background_selected_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('css_module_link_selected_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
                ('logo_max_height', models.SmallIntegerField()),
                ('logo_max_width', models.SmallIntegerField()),
                ('foldable_apps', models.BooleanField()),
                ('language_chooser_control', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('list_filter_highlight', models.BooleanField()),
                ('list_filter_removal_links', models.BooleanField()),
                ('show_fieldsets_as_tabs', models.BooleanField()),
                ('show_inlines_as_tabs', models.BooleanField()),
                ('css_generic_link_active_color', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10)),
            ],
            options={
                'db_table': 'admin_interface_theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('idbanco', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreclib', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=40, null=True)),
                ('apellidoclib', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=40, null=True)),
                ('telefonoclib', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=40, null=True)),
                ('emailclib', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('direclib', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('hipoteca', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'BANCO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrecli', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=40, null=True)),
                ('apellidocli', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=40, null=True)),
                ('telefonocli', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=40, null=True)),
                ('emailcli', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('direcli', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('servicio', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Modern_Spanish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Modern_Spanish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eqinsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idequipo', models.IntegerField()),
                ('nombres', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('estadoequipo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EQINSP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idinspeccion', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=250, null=True)),
                ('idusuario', models.IntegerField(blank=True, null=True)),
                ('idequipo', models.IntegerField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('fechains', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'INSPECCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogHistorialcliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='FECHA', null=True)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DESCRIPCION', max_length=40, null=True)),
                ('usuario', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='USUARIO', max_length=20, null=True)),
            ],
            options={
                'db_table': 'LOG_HISTORIALCLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogHistorialeqinsp',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='FECHA', null=True)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DESCRIPCION', max_length=40, null=True)),
                ('usuario', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='USUARIO', max_length=20, null=True)),
            ],
            options={
                'db_table': 'LOG_HISTORIALEQINSP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsalida', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('idequipo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SALIDA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('run_cli', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=12)),
                ('run_emp', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=12)),
                ('tipo_solicitud', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=300)),
                ('fecha_solicitud', models.DateField()),
            ],
            options={
                'db_table': 'SOLICITUD',
                'managed': False,
            },
        ),
    ]
