# Generated by Django 4.1.9 on 2023-05-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'managed': True},
        ),
    ]
